from zone_energy.models import (
    Interaction,
    InteractionState,
    Reversal,
    Zone,
    ZoneState,
)


class ZoneFactory:
    """
    Creates a new Zone together with its initial OPEN interaction.

    IDs are generated by the Engine and passed into the factory.
    """

    @staticmethod
    def create(
        zone_id: int,
        interaction_id: int,
        reversal: Reversal,
        lower_price: float,
        upper_price: float,
        previous_zone_id: int | None = None,
    ) -> Zone:

        interaction = Interaction(
            id=interaction_id,
            zone_id=zone_id,
            state=InteractionState.OPEN,
            start_price=reversal.extreme_price,
            start_index=reversal.extreme_index,
        )

        zone = Zone(
            id=zone_id,
            type=reversal.type,
            state=ZoneState.ACTIVE,
            lower_price=lower_price,
            upper_price=upper_price,
            creation_extreme=reversal.extreme_price,
            creation_index=reversal.extreme_index,
            interactions=[interaction],
            previous_zone_id=previous_zone_id,
            created_at_index=reversal.detection_index,
            last_interaction_origin_index=reversal.extreme_index,
        )

        return zone